import { createSlice, PayloadAction } from "@reduxjs/toolkit";

interface CardItem {
  id: number;
  title: string;
  price: string;
  location: string;
  size: string;
  rooms: number;
  baths: number;
  image: string;
  forSale: boolean;
  datePosted: string;
  features: string[];
}

interface CardsState {
  items: CardItem[];
}

const initialState: CardsState = {
  items: [
    {
      id: 1,
      title: "דופלקס להשכרה ברמת גן",
      price: "80,000 ₪ / חודש",
      location: "שכונה 38 רמת גן",
      size: '100 מ"ר',
      rooms: 8,
      baths: 4,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-01-27",
      features: ["מרפסת", "חניה"],
    },
    {
      id: 2,
      title: "דופלקס להשכרה ברמת גן",
      price: "40,000 ₪ / חודש",
      location: "שכונה 4, רמת גן",
      size: '100 מ"ר',
      rooms: 30,
      baths: 2,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-05-26",
      features: ["מחסן"],
    },
    {
      id: 3,
      title: "דופלקס להשכרה ברמת גן",
      price: "900,000 ₪ / חודש",
      location: "שכונה 39 רמת גן",
      size: '100 מ"ר',
      rooms: 32,
      baths: 10,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-05-12",
      features: ["מחסן"],
    },
    {
      id: 4,
      title: "דופלקס להשכרה ברמת גן",
      price: "200,000 ₪ / חודש",
      location: "שכונה 310 רמת גן",
      size: '100 מ"ר',
      rooms: 38,
      baths: 89,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-05-28",
      features: ["מחסן"],
    },
    {
      id: 5,
      title: "דופלקס להשכרה ברמת גן",
      price: "700,000 ₪ / חודש",
      location: "שכונה 22, רמת גן",
      size: '100 מ"ר',
      rooms: 34,
      baths: 100,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-04-27",
      features: ["חניה", "מחסן"],
    },
    {
      id: 6,
      title: "דופלקס להשכרה ברמת גן",
      price: "300,000 ₪ / חודש",
      location: "שכונה 10, רמת גן",
      size: '120 מ"ר',
      rooms: 71,
      baths: 220,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-04-26",
      features: ["חניה", "מחסן"],
    },
    {
      id: 7,
      title: "דופלקס להשכרה ברמת גן",
      price: "350,000 ₪ / חודש",
      location: "שכונה 4, רמת גן",
      size: '122 מ"ר',
      rooms: 79,
      baths: 223,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-07-08",
      features: ["חניה", "מחסן"],
    },
    {
      id: 8,
      title: "דופלקס להשכרה ברמת גן",
      price: "420,000 ₪ / חודש",
      location: "שכונה 3, רמת גן",
      size: '229 מ"ר',
      rooms: 61,
      baths: 220,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-07-29",
      features: ["מחסן", "מעלית"],
    },
    {
      id: 9,
      title: "דופלקס להשכרה ברמת גן",
      price: "50,000 ₪ / חודש",
      location: "שכונה 7, רמת גן",
      size: '240 מ"ר',
      rooms: 71,
      baths: 133,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-04-09",
      features: ["מחסן", "מעלית"],
    },
    {
      id: 10,
      title: "דופלקס להשכרה ברמת גן",
      price: "300,000 ₪ / חודש",
      location: "שכונה 8, רמת גן",
      size: '120 מ"ר',
      rooms: 42,
      baths: 20,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-03-16",
      features: ["מעלית"],
    },
    {
      id: 11,
      title: "דופלקס להשכרה ברמת גן",
      price: "830,000 ₪ / חודש",
      location: "שכונה 70, רמת גן",
      size: '340 מ"ר',
      rooms: 47,
      baths: 150,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-06-15",
      features: ["מעלית"],
    },
    {
      id: 12,
      title: "דירה חדשה מספר 12",
      price: "695,249 ₪ / חודש",
      location: "שכונה 69, רמת גן",
      size: '230 מ"ר',
      rooms: 8,
      baths: 3,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-01-23",
      features: ["מרפסת"],
    },
    {
      id: 13,
      title: "דירה חדשה מספר 13",
      price: "748,647 ₪ / חודש",
      location: "שכונה 73, רמת גן",
      size: '128 מ"ר',
      rooms: 8,
      baths: 2,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-04-27",
      features: ["מרפסת"],
    },
    {
      id: 14,
      title: "דירה חדשה מספר 14",
      price: "849,093 ₪ / חודש",
      location: "שכונה 30, רמת גן",
      size: '119 מ"ר',
      rooms: 5,
      baths: 1,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-03-13",
      features: ["מרפסת", "מעלית", "מחסן"],
    },
    {
      id: 15,
      title: "דירה חדשה מספר 15",
      price: "669,970 ₪ / חודש",
      location: "שכונה 37, רמת גן",
      size: '140 מ"ר',
      rooms: 4,
      baths: 4,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-06-16",
      features: ["מרפסת", "מעלית", "מחסן"],
    },
    {
      id: 16,
      title: "דירה חדשה מספר 16",
      price: "281,006 ₪ / חודש",
      location: "שכונה 64, רמת גן",
      size: '178 מ"ר',
      rooms: 3,
      baths: 3,
      image: "./assets/hous.avif",
      forSale: false,
      datePosted: "2024-01-28",
      features: ["חניה", "מעלית", "מחסן"],
    },
    {
      id: 17,
      title: "דירה חדשה מספר 17",
      price: "401,790 ₪ / חודש",
      location: "שכונה 99,תל אביב",
      size: '135 מ"ר',
      rooms: 9,
      baths: 2,
      image: "./assets/hous.avif",
      forSale: true,
      datePosted: "2024-01-10",
      features: ["חניה", "מעלית", "מחסן"],
    },
    // Add more if needed
  ],
};

const cardsSlice = createSlice({
  name: "cards",
  initialState,
  reducers: {
    setCards(state, action: PayloadAction<CardItem[]>) {
      state.items = action.payload;
    },
  },
});

export const { setCards } = cardsSlice.actions;
export default cardsSlice.reducer;
